/**
 * \file
 *
 * \brief USI Host - G3 General definitions
 *
 * Copyright (c) 2021 Microchip Technology Inc. and its subsidiaries.
 *
 * \asf_license_start
 *
 * \page License
 *
 * Subject to your compliance with these terms, you may use Microchip
 * software and any derivatives exclusively with Microchip products.
 * It is your responsibility to comply with third party license terms applicable
 * to your use of third party software (including open source software) that
 * may accompany Microchip software.
 *
 * THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE,
 * INCLUDING ANY IMPLIED WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY,
 * AND FITNESS FOR A PARTICULAR PURPOSE. IN NO EVENT WILL MICROCHIP BE
 * LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, INCIDENTAL OR CONSEQUENTIAL
 * LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND WHATSOEVER RELATED TO THE
 * SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS BEEN ADVISED OF THE
 * POSSIBILITY OR THE DAMAGES ARE FORESEEABLE.  TO THE FULLEST EXTENT
 * ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN ANY WAY
 * RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
 * THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 * \asf_license_stop
 *
 */
 /*
 * Support and FAQ: visit <a href="https://www.microchip.com/support/">Microchip Support</a>
 */

#ifndef G3H
#define G3H

#include <stdint.h>
#include <stdio.h>

/* Enable traces to show them in console stderr (0 or 1)*/
#define G3_DEBUG_TRACES 1

#define LOG_G3_DEBUG(...) if (G3_DEBUG_TRACES) {fprintf(stderr, __VA_ARGS__); }	\
	fflush(stdout)

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------- */
/* Generics of G3 */
/* #define G3_MAC_LENGTH							6		///< Length in bytes of EUI48 identifier of a Node */
#define G3_SYNC_TIMEOUT 3 /* Seconds */

/* USI */
/* #define CMD_G3_PROTOCOL_MSK			0x3F */
/* #define CMD_G3_PROTOCOL(A)				((A)&CMD_PRIME_PROTOCOL_MSK) */

/* ************************************************************** */
/*	G3	CONTROL */
/* ************************************************************** */
void g3_Init(void);
void g3_Start(void);
void g3_Process(void);
void g3_Upd1msInt(void);
void g3_Upd618msInt(void);

/* ************************************************************** */
/*	COMMANDS */
/* ************************************************************** */

#define G3_SERIAL_MSG_STATUS                       0

/* COORDINATOR ACCESS */
#define G3_SERIAL_MSG_COORD_REQUEST_MESSAGES_BEGIN  1

#define G3_SERIAL_MSG_COORD_INITIALIZE              (G3_SERIAL_MSG_COORD_REQUEST_MESSAGES_BEGIN)
#define G3_SERIAL_MSG_COORD_SET_REQUEST             (G3_SERIAL_MSG_COORD_REQUEST_MESSAGES_BEGIN + 1)
#define G3_SERIAL_MSG_COORD_GET_REQUEST             (G3_SERIAL_MSG_COORD_REQUEST_MESSAGES_BEGIN + 2)
#define G3_SERIAL_MSG_COORD_KICK_REQUEST            (G3_SERIAL_MSG_COORD_REQUEST_MESSAGES_BEGIN + 3)
#define G3_SERIAL_MSG_COORD_REKEYING_REQUEST        (G3_SERIAL_MSG_COORD_REQUEST_MESSAGES_BEGIN + 4)

#define G3_SERIAL_MSG_COORD_CONF_IND_MESSAGES_BEGIN (G3_SERIAL_MSG_COORD_REQUEST_MESSAGES_BEGIN + 5)
#define G3_SERIAL_MSG_COORD_SET_CONFIRM             (G3_SERIAL_MSG_COORD_CONF_IND_MESSAGES_BEGIN)
#define G3_SERIAL_MSG_COORD_GET_CONFIRM             (G3_SERIAL_MSG_COORD_CONF_IND_MESSAGES_BEGIN + 1)
#define G3_SERIAL_MSG_COORD_JOIN_INDICATION         (G3_SERIAL_MSG_COORD_CONF_IND_MESSAGES_BEGIN + 2)
#define G3_SERIAL_MSG_COORD_LEAVE_INDICATION        (G3_SERIAL_MSG_COORD_CONF_IND_MESSAGES_BEGIN + 3)

#define G3_SERIAL_MSG_COORD_REQUEST_MESSAGES_END    (G3_SERIAL_MSG_COORD_LEAVE_INDICATION)

/* ADP ACCESS */
#define G3_SERIAL_MSG_ADP_REQUEST_MESSAGES_BEGIN   10
#define G3_SERIAL_MSG_ADP_INITIALIZE               (G3_SERIAL_MSG_ADP_REQUEST_MESSAGES_BEGIN)
#define G3_SERIAL_MSG_ADP_DATA_REQUEST             (G3_SERIAL_MSG_ADP_REQUEST_MESSAGES_BEGIN + 1)
#define G3_SERIAL_MSG_ADP_DISCOVERY_REQUEST        (G3_SERIAL_MSG_ADP_REQUEST_MESSAGES_BEGIN + 2)
#define G3_SERIAL_MSG_ADP_NETWORK_START_REQUEST    (G3_SERIAL_MSG_ADP_REQUEST_MESSAGES_BEGIN + 3)
#define G3_SERIAL_MSG_ADP_NETWORK_JOIN_REQUEST     (G3_SERIAL_MSG_ADP_REQUEST_MESSAGES_BEGIN + 4)
#define G3_SERIAL_MSG_ADP_NETWORK_LEAVE_REQUEST    (G3_SERIAL_MSG_ADP_REQUEST_MESSAGES_BEGIN + 5)
#define G3_SERIAL_MSG_ADP_RESET_REQUEST            (G3_SERIAL_MSG_ADP_REQUEST_MESSAGES_BEGIN + 6)
#define G3_SERIAL_MSG_ADP_SET_REQUEST              (G3_SERIAL_MSG_ADP_REQUEST_MESSAGES_BEGIN + 7)
#define G3_SERIAL_MSG_ADP_GET_REQUEST              (G3_SERIAL_MSG_ADP_REQUEST_MESSAGES_BEGIN + 8)
#define G3_SERIAL_MSG_ADP_LBP_REQUEST              (G3_SERIAL_MSG_ADP_REQUEST_MESSAGES_BEGIN + 9)
#define G3_SERIAL_MSG_ADP_ROUTE_DISCOVERY_REQUEST  (G3_SERIAL_MSG_ADP_REQUEST_MESSAGES_BEGIN + 10)
#define G3_SERIAL_MSG_ADP_PATH_DISCOVERY_REQUEST   (G3_SERIAL_MSG_ADP_REQUEST_MESSAGES_BEGIN + 11)
#define G3_SERIAL_MSG_ADP_MAC_SET_REQUEST          (G3_SERIAL_MSG_ADP_REQUEST_MESSAGES_BEGIN + 12)
#define G3_SERIAL_MSG_ADP_MAC_GET_REQUEST          (G3_SERIAL_MSG_ADP_REQUEST_MESSAGES_BEGIN + 13)
#define G3_SERIAL_MSG_ADP_REQUEST_MESSAGES_END     (G3_SERIAL_MSG_ADP_MAC_GET_REQUEST)

#define G3_SERIAL_MSG_ADP_CONF_IND_MESSAGES_BEGIN   30
#define G3_SERIAL_MSG_ADP_DATA_CONFIRM              (G3_SERIAL_MSG_ADP_CONF_IND_MESSAGES_BEGIN)
#define G3_SERIAL_MSG_ADP_DATA_INDICATION           (G3_SERIAL_MSG_ADP_CONF_IND_MESSAGES_BEGIN + 1)
#define G3_SERIAL_MSG_ADP_NETWORK_STATUS_INDICATION (G3_SERIAL_MSG_ADP_CONF_IND_MESSAGES_BEGIN + 2)
#define G3_SERIAL_MSG_ADP_DISCOVERY_CONFIRM         (G3_SERIAL_MSG_ADP_CONF_IND_MESSAGES_BEGIN + 3)
#define G3_SERIAL_MSG_ADP_NETWORK_START_CONFIRM     (G3_SERIAL_MSG_ADP_CONF_IND_MESSAGES_BEGIN + 4)
#define G3_SERIAL_MSG_ADP_NETWORK_JOIN_CONFIRM      (G3_SERIAL_MSG_ADP_CONF_IND_MESSAGES_BEGIN + 5)
#define G3_SERIAL_MSG_ADP_NETWORK_LEAVE_CONFIRM     (G3_SERIAL_MSG_ADP_CONF_IND_MESSAGES_BEGIN + 6)
#define G3_SERIAL_MSG_ADP_NETWORK_LEAVE_INDICATION  (G3_SERIAL_MSG_ADP_CONF_IND_MESSAGES_BEGIN + 7)
#define G3_SERIAL_MSG_ADP_RESET_CONFIRM             (G3_SERIAL_MSG_ADP_CONF_IND_MESSAGES_BEGIN + 8)
#define G3_SERIAL_MSG_ADP_SET_CONFIRM               (G3_SERIAL_MSG_ADP_CONF_IND_MESSAGES_BEGIN + 9)
#define G3_SERIAL_MSG_ADP_GET_CONFIRM               (G3_SERIAL_MSG_ADP_CONF_IND_MESSAGES_BEGIN + 10)
#define G3_SERIAL_MSG_ADP_LBP_CONFIRM               (G3_SERIAL_MSG_ADP_CONF_IND_MESSAGES_BEGIN + 11)
#define G3_SERIAL_MSG_ADP_LBP_INDICATION            (G3_SERIAL_MSG_ADP_CONF_IND_MESSAGES_BEGIN + 12)
#define G3_SERIAL_MSG_ADP_ROUTE_DISCOVERY_CONFIRM   (G3_SERIAL_MSG_ADP_CONF_IND_MESSAGES_BEGIN + 13)
#define G3_SERIAL_MSG_ADP_PATH_DISCOVERY_CONFIRM    (G3_SERIAL_MSG_ADP_CONF_IND_MESSAGES_BEGIN + 14)
#define G3_SERIAL_MSG_ADP_MAC_SET_CONFIRM           (G3_SERIAL_MSG_ADP_CONF_IND_MESSAGES_BEGIN + 15)
#define G3_SERIAL_MSG_ADP_MAC_GET_CONFIRM           (G3_SERIAL_MSG_ADP_CONF_IND_MESSAGES_BEGIN + 16)
#define G3_SERIAL_MSG_ADP_BUFFER_INDICATION         (G3_SERIAL_MSG_ADP_CONF_IND_MESSAGES_BEGIN + 17)
#define G3_SERIAL_MSG_ADP_DISCOVERY_INDICATION      (G3_SERIAL_MSG_ADP_CONF_IND_MESSAGES_BEGIN + 18)
#define G3_SERIAL_MSG_ADP_PREQ_INDICATION           (G3_SERIAL_MSG_ADP_CONF_IND_MESSAGES_BEGIN + 19)
#define G3_SERIAL_MSG_ADP_UPD_NON_VOLATILE_DATA_INDICATION  (G3_SERIAL_MSG_ADP_CONF_IND_MESSAGES_BEGIN + 20)
#define G3_SERIAL_MSG_ADP_ROUTE_NOT_FOUND_INDICATION        (G3_SERIAL_MSG_ADP_CONF_IND_MESSAGES_BEGIN + 21)

/* MAC ACCESS */
#define G3_SERIAL_MSG_MAC_REQUEST_MESSAGES_BEGIN   50
#define G3_SERIAL_MSG_MAC_INITIALIZE               (G3_SERIAL_MSG_MAC_REQUEST_MESSAGES_BEGIN)
#define G3_SERIAL_MSG_MAC_DATA_REQUEST             (G3_SERIAL_MSG_MAC_REQUEST_MESSAGES_BEGIN + 1)
#define G3_SERIAL_MSG_MAC_GET_REQUEST              (G3_SERIAL_MSG_MAC_REQUEST_MESSAGES_BEGIN + 2)
#define G3_SERIAL_MSG_MAC_SET_REQUEST              (G3_SERIAL_MSG_MAC_REQUEST_MESSAGES_BEGIN + 3)
#define G3_SERIAL_MSG_MAC_RESET_REQUEST            (G3_SERIAL_MSG_MAC_REQUEST_MESSAGES_BEGIN + 4)
#define G3_SERIAL_MSG_MAC_SCAN_REQUEST             (G3_SERIAL_MSG_MAC_REQUEST_MESSAGES_BEGIN + 5)
#define G3_SERIAL_MSG_MAC_START_REQUEST            (G3_SERIAL_MSG_MAC_REQUEST_MESSAGES_BEGIN + 6)
#define G3_SERIAL_MSG_MAC_REQUEST_MESSAGES_END     (G3_SERIAL_MSG_MAC_START_REQUEST)

#define G3_SERIAL_MSG_MAC_CONF_IND_MESSAGES_BEGIN  60
#define G3_SERIAL_MSG_MAC_DATA_CONFIRM             (G3_SERIAL_MSG_MAC_CONF_IND_MESSAGES_BEGIN)
#define G3_SERIAL_MSG_MAC_DATA_INDICATION          (G3_SERIAL_MSG_MAC_CONF_IND_MESSAGES_BEGIN + 1)
#define G3_SERIAL_MSG_MAC_GET_CONFIRM              (G3_SERIAL_MSG_MAC_CONF_IND_MESSAGES_BEGIN + 2)
#define G3_SERIAL_MSG_MAC_SET_CONFIRM              (G3_SERIAL_MSG_MAC_CONF_IND_MESSAGES_BEGIN + 3)
#define G3_SERIAL_MSG_MAC_RESET_CONFIRM            (G3_SERIAL_MSG_MAC_CONF_IND_MESSAGES_BEGIN + 4)
#define G3_SERIAL_MSG_MAC_SCAN_CONFIRM             (G3_SERIAL_MSG_MAC_CONF_IND_MESSAGES_BEGIN + 5)
#define G3_SERIAL_MSG_MAC_BEACON_NOTIFY            (G3_SERIAL_MSG_MAC_CONF_IND_MESSAGES_BEGIN + 6)
#define G3_SERIAL_MSG_MAC_START_CONFIRM            (G3_SERIAL_MSG_MAC_CONF_IND_MESSAGES_BEGIN + 7)
#define G3_SERIAL_MSG_MAC_COMM_STATUS_INDICATION   (G3_SERIAL_MSG_MAC_CONF_IND_MESSAGES_BEGIN + 8)
#define G3_SERIAL_MSG_MAC_SNIFFER_INDICATION       (G3_SERIAL_MSG_MAC_CONF_IND_MESSAGES_BEGIN + 9)

#ifdef G3_HYBRID_PROFILE
/* MAC RF ACCESS */
#define G3_SERIAL_MSG_MAC_REQUEST_MESSAGES_BEGIN_RF   30
#define G3_SERIAL_MSG_MAC_INITIALIZE_RF               (G3_SERIAL_MSG_MAC_REQUEST_MESSAGES_BEGIN_RF)
#define G3_SERIAL_MSG_MAC_DATA_REQUEST_RF             (G3_SERIAL_MSG_MAC_REQUEST_MESSAGES_BEGIN_RF + 1)
#define G3_SERIAL_MSG_MAC_GET_REQUEST_RF              (G3_SERIAL_MSG_MAC_REQUEST_MESSAGES_BEGIN_RF + 2)
#define G3_SERIAL_MSG_MAC_SET_REQUEST_RF              (G3_SERIAL_MSG_MAC_REQUEST_MESSAGES_BEGIN_RF + 3)
#define G3_SERIAL_MSG_MAC_RESET_REQUEST_RF            (G3_SERIAL_MSG_MAC_REQUEST_MESSAGES_BEGIN_RF + 4)
#define G3_SERIAL_MSG_MAC_SCAN_REQUEST_RF             (G3_SERIAL_MSG_MAC_REQUEST_MESSAGES_BEGIN_RF + 5)
#define G3_SERIAL_MSG_MAC_START_REQUEST_RF            (G3_SERIAL_MSG_MAC_REQUEST_MESSAGES_BEGIN_RF + 6)
#define G3_SERIAL_MSG_MAC_REQUEST_MESSAGES_END_RF     (G3_SERIAL_MSG_MAC_START_REQUEST_RF)

#define G3_SERIAL_MSG_MAC_CONF_IND_MESSAGES_BEGIN_RF  40
#define G3_SERIAL_MSG_MAC_DATA_CONFIRM_RF             (G3_SERIAL_MSG_MAC_CONF_IND_MESSAGES_BEGIN_RF)
#define G3_SERIAL_MSG_MAC_DATA_INDICATION_RF          (G3_SERIAL_MSG_MAC_CONF_IND_MESSAGES_BEGIN_RF + 1)
#define G3_SERIAL_MSG_MAC_GET_CONFIRM_RF              (G3_SERIAL_MSG_MAC_CONF_IND_MESSAGES_BEGIN_RF + 2)
#define G3_SERIAL_MSG_MAC_SET_CONFIRM_RF              (G3_SERIAL_MSG_MAC_CONF_IND_MESSAGES_BEGIN_RF + 3)
#define G3_SERIAL_MSG_MAC_RESET_CONFIRM_RF            (G3_SERIAL_MSG_MAC_CONF_IND_MESSAGES_BEGIN_RF + 4)
#define G3_SERIAL_MSG_MAC_SCAN_CONFIRM_RF             (G3_SERIAL_MSG_MAC_CONF_IND_MESSAGES_BEGIN_RF + 5)
#define G3_SERIAL_MSG_MAC_BEACON_NOTIFY_RF            (G3_SERIAL_MSG_MAC_CONF_IND_MESSAGES_BEGIN_RF + 6)
#define G3_SERIAL_MSG_MAC_START_CONFIRM_RF            (G3_SERIAL_MSG_MAC_CONF_IND_MESSAGES_BEGIN_RF + 7)
#define G3_SERIAL_MSG_MAC_COMM_STATUS_INDICATION_RF   (G3_SERIAL_MSG_MAC_CONF_IND_MESSAGES_BEGIN_RF + 8)
#endif

/* ------------------------------------- */
/*	Constants */
/* MAX Buffer size to transmit or receive data */
#define G3_MACSAP_DATA_SIZE     1024
#define G3_ADPSAP_DATA_SIZE     1024
#define G3_COORDSAP_DATA_SIZE   1024

/* Other buffer sizes */
#define MAX_SIZE_ADDR_G3        4
#define MAX_HOPS                16

/* ------------------------------------- */
/* / Protocol ID to serialize (USI) */
#define PROTOCOL_SNIF_G3                        0x23
#define PROTOCOL_MAC_G3                         0x24
#define PROTOCOL_ADP_G3                         0x25
#define PROTOCOL_COORD_G3                       0x26

/* Status codes related to HostInterface processing */
enum ESerialStatus {
	SERIAL_STATUS_SUCCESS = 0,
	SERIAL_STATUS_NOT_ALLOWED,
	SERIAL_STATUS_UNKNOWN_COMMAND,
	SERIAL_STATUS_INVALID_PARAMETER
};

/* General functions */
/* - For received commands */
uint8_t g3_MAC_receivedCmd(uint8_t *buf, uint16_t len);
uint8_t g3_ADP_receivedCmd(uint8_t *buf, uint16_t len);
uint8_t g3_COORD_receivedCmd(uint8_t *buf, uint16_t len);

/* Functions to resolve endianness in different platforms */
void mem_copy_to_usi_endianness_uint32( uint8_t *puc_dst, uint8_t *puc_src);
void mem_copy_to_usi_endianness_uint16( uint8_t *puc_dst, uint8_t *puc_src);
void mem_copy_from_usi_endianness_uint32(uint8_t *puc_src, uint8_t *puc_dst);
void mem_copy_from_usi_endianness_uint16(uint8_t *puc_src, uint8_t *puc_dst);
#ifdef __cplusplus
}
#endif

#endif
